version: "3"
services:
  app_1:
    image: spring:1.0
    build:
      context: .
      dockerfile: Dockerfile

  app_2:
    image: spring:2.0
    build:
      context: .
      dockerfile: Dockerfile_02